import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Slim-fit vest in drapey twill",
    brand: "Slim Fit",
    price: 1440,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BR253_WZ3180?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 1800,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Women's Skinny Jeans",
    brand: "Slim Fit",
    price: 1440,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BK399_DM6196?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 1800,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Women's Cardigan",
    brand: "Cozy Knits",
    price: 1344,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BO154_BL8133?hei=540&crop=0,0,680,0",
    rating: 4,
    strikePrice: 2240,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Women's Summer Dress",
    brand: "Sunshine Fashion",
    price: 1764,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BP844_RD5285_m?hei=540&crop=0,0,680,0",
    rating: 1,
    strikePrice: 2940,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Elegant Women's Dress",
    brand: "Fashionista",
    price: 2940,
    categoryName: "Women's Clothing",
    image_url: "https://jcrew.com/s7-img-facade/BR467_BL8227?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 4900,
    off: 40,
  },
  {
    _id: uuid(),
    name: "NEW Louisa lady jacket in lightweight chino",
    brand: "Fashionista",
    price: 2940,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BR075_PK5249?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 4900,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Casual Women's Top",
    brand: "Trendy Chic",
    price: 1188,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BM926_BK0001?hei=540&crop=0,0,680,0",
    rating: 3,
    strikePrice: 1320,
    off: 10,
  },
  {
    _id: uuid(),
    name: "Formal Women's Blazer",
    brand: "Classy Attire",
    price: 3375,
    categoryName: "Women's Clothing",
    image_url:
      "https://img.freepik.com/free-photo/portrait-young-japanese-woman_23-2148870710.jpg?w=540&t=st=1684691528~exp=1684692128~hmac=c9d7eeeec142b11a9b405d5db741cffa3b3838df55cae7be4a5c9fb6a6391444",
    rating: 4,
    strikePrice: 6750,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Women's Floral Print Dress",
    brand: "Blossom Fashion",
    description:
      "This easy dress also features a cute bow detail at the center and is made in breathable, 100 percent linen.",
    price: 1350,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BQ601_PT3457_d3?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 2700,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Trouser Essential",
    brand: "Digital Printed",
    description:
      "A totally essential pant. Our drapey trousers go from workdays to weekends, effortlessly. This pair features a slightly tapered",
    price: 1562,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BR709_WZ3180?hei=540&crop=0,0,680,0",
    rating: 1,
    strikePrice: 1952,
    off: 20,
  },
  {
    _id: uuid(),
    name: "frock gold printed",
    brand: "Ghazi Fabric",
    description: "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
    price: 189,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BR447_YL5600?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 270,
    off: 30,
  },
  {
    _id: uuid(),
    name: "Ladies Multicolored Dress",
    brand: "Ghazi Fabric",
    description:
      "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
    price: 2191,
    categoryName: "Women's Clothing",
    image_url: "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
    rating: 1,
    strikePrice: 4383,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Sleeve Shirt Womens",
    brand: "Professional Wear",
    description:
      "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
    price: 2955,
    categoryName: "Women's Clothing",
    image_url: "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
    rating: 4,
    strikePrice: 3283,
    off: 10,
  },
  {
    _id: uuid(),
    name: "Women Sweaters Wool",
    brand: "Top Sweater",
    description:
      "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater",
    price: 1944,
    categoryName: "Women's Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BO158_GR8247?hei=540&crop=0,0,680,0",
    rating: 1,
    strikePrice: 3889,
    off: 50,
  },
  {
    _id: uuid(),
    name: "women winter clothes",
    brand: "Top Sweater",
    description:
      "women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set",
    price: 768,
    categoryName: "Women's Clothing",
    image_url: "https://i.dummyjson.com/data/products/40/thumbnail.jpg",
    rating: 4,
    strikePrice: 1536,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Classic Relaxed-fit chino pant",
    brand: "Nike",
    price: 858,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE611_WZ2044_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 1716,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Woven belt",
    brand: "Jcrew",
    price: 705,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AK786_PP1488?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 2,
    strikePrice: 783,
    off: 10,
  },
  {
    _id: uuid(),
    name: "Italian linen-cotton blazer",
    brand: "JCREW",
    price: 1649,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE437_WZ1782_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 1832,
    off: 10,
  },
  {
    _id: uuid(),
    name: "Short-sleeve Shirt",
    brand: "Adiddas",
    price: 1437,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE986_WX0596_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 1,
    strikePrice: 2875,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Stretch chino shorts",
    brand: "Nike",
    price: 1174,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE051_WZ2044_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 4,
    strikePrice: 2349,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Classic Relaxed-fit pleated chino pant",
    brand: "Puma",
    price: 75,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE612_WZ1914_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 2,
    strikePrice: 151,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Classic Relaxed-fit pleated chino",
    brand: "Nike",
    price: 1576,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE612_WZ1914_d3?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 2627,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Camden loafers in leather",
    brand: "Nike",
    price: 109,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AV166_PP3360?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 4,
    strikePrice: 156,
    off: 30,
  },
  {
    _id: uuid(),
    name: "Hemp-organic cotton long-sleeve T-shirt",
    brand: "JCREW",
    price: 900,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BH814_RD6243?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    rating: 3,
    strikePrice: 1125,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Reversible bucket hat in linen-cotton",
    brand: "JCREW",
    price: 381,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BH134_WZ1782?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 762,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Made-in-the-USA watercolor sardine graphic T-shirt",
    brand: "JCREW",
    price: 1880,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BI763_PP3626_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 2,
    strikePrice: 2350,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Secret Wash organic cotton poplin shirt",
    brand: "Adiddas",
    price: 182,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BF793_PP1744?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    rating: 1,
    strikePrice: 202,
    off: 10,
  },
  {
    _id: uuid(),
    name: "O-ring cotton rope belt",
    brand: "Puma",
    price: 1145,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BH030_BR6578?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    rating: 4,
    strikePrice: 2290,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Silk tie",
    brand: "JCREW",
    price: 1077,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AX110_NT4546?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    rating: 2,
    strikePrice: 2155,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Pajama shirt in cotton poplin",
    brand: "Nike",
    price: 332,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AZ595_WD4807_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 1,
    strikePrice: 475,
    off: 30,
  },
  {
    _id: uuid(),
    name: "Flannel pajama pant",
    brand: "Puma",
    price: 2458,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AZ665_WX8063_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 4097,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Broken-in short-sleeve V-neck T-shirt",
    brand: "Puma",
    price: 2580,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AH919_BL8133_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 1,
    strikePrice: 2867,
    off: 10,
  },
  {
    _id: uuid(),
    name: "Bowery wrinkle-free stretch cotton shirt with spread collar",
    brand: "JCREW",
    price: 1361,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AV828_WT0002_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 2269,
    off: 40,
  },
  {
    _id: uuid(),
    name: "770™ Straight-fit stretch chino pant",
    brand: "Adiddas",
    price: 173,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/E1590_GY7317_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 3,
    strikePrice: 289,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Garment-dyed slub cotton polo shirt",
    brand: "Nike",
    price: 919,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/J1851_BL9137_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 1,
    strikePrice: 1149,
    off: 20,
  },
  {
    _id: uuid(),
    name: "484 Slim-fit garment-dyed five-pocket pant",
    brand: "Nike",
    price: 570,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/AZ963_WZ2335_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 4,
    strikePrice: 633,
    off: 10,
  },
  {
    _id: uuid(),
    name: "Short-sleeve slub cotton shirt",
    brand: "JCREW",
    price: 2036,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BE958_PT1454?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    rating: 3,
    strikePrice: 2545,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Leather billfold wallet",
    brand: "Reebok",
    price: 339,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BA766_PP2015?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=480&hei=480",
    rating: 1,
    strikePrice: 484,
    off: 30,
  },
  {
    _id: uuid(),
    name: "Ludlow Classic-fit suit jacket in Italian stretch four-season wool",
    brand: "JCREW",
    price: 1878,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/J3274_WW8804_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 4,
    strikePrice: 3757,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Ludlow Classic-fit tuxedo pant in Italian wool",
    brand: "JCREW",
    price: 746,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/C3309_BK0001_d3?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 4,
    strikePrice: 1244,
    off: 40,
  },
  {
    _id: uuid(),
    name: "Ludlow Slim-fit unstructured suit pant in Irish cotton-linen",
    brand: "Reebok",
    price: 181,
    categoryName: "Men's Clothing",
    image_url:
      "https://www.jcrew.com/s7-img-facade/BC552_WZ1778_m?fmt=jpeg&qlt=90,0&resMode=sharp&op_usm=.1,0,0,0&crop=0,0,0,0&wid=540&hei=540",
    rating: 2,
    strikePrice: 226,
    off: 20,
  },
  {
    _id: uuid(),
    name: "sublimation plain kids tank",
    brand: "Soft Cotton",
    description: "sublimation plain kids tank tops wholesale",
    price: 498,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BQ485_KF6238?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 997,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Kids' Denim Shorts",
    brand: "Cool Kids",
    price: 455,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/AI454_GR6726?hei=540&crop=0,0,680,0",
    rating: 2,
    strikePrice: 650,
    off: 30,
  },
  {
    _id: uuid(),
    name: "Kids' Printed T-Shirt",
    brand: "Happy Prints",
    price: 384,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BO352_GP0320?hei=540&crop=0,0,680,0",
    rating: 3,
    strikePrice: 480,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Kids' Sportswear Set",
    brand: "Active Kids",
    price: 768,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BC371_KF3439?hei=540&crop=0,0,680,0",
    rating: 5,
    strikePrice: 960,
    off: 20,
  },
  {
    _id: uuid(),
    name: "Comfortable Kids' T-Shirt",
    brand: "Little Explorers",
    price: 187,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/J1960_GY6668_m?hei=540&crop=0,0,680,0",
    rating: 3,
    strikePrice: 375,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Adorable Kids' Dress",
    brand: "Tiny Trends",
    price: 600,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BJ555_KF5019?hei=540&crop=0,0,680,0",
    rating: 5,
    strikePrice: 1200,
    off: 50,
  },
  {
    _id: uuid(),
    name: "Kids' Sweatshirt",
    brand: "Playful Kids",
    price: 450,
    categoryName: "Kids Clothing",
    image_url: "https://www.jcrew.com/s7-img-facade/BJ863_SR0271?hei=540&crop=0,0,680,0",
    rating: 3,
    strikePrice: 900,
    off: 50,
  },
];
