import {v4 as uuid} from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Premium Men's Clothes",
    brand: "Shiv Khera",
    price: "5000",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Elegant Women's Dress",
    brand: "Fashionista",
    price: "3500",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Comfortable Kids' T-Shirt",
    brand: "Little Explorers",
    price: "250",
    categoryName: "Kids' Clothing",
  },
  {
    _id: uuid(),
    title: "Stylish Sneakers",
    brand: "FootFlex",
    price: "1200",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    title: "Trendy Sunglasses",
    brand: "ShadeMaster",
    price: "500",
    categoryName: "Accessories",
  },
  {
    _id: uuid(),
    title: "Stylish Men's Shirt",
    brand: "Fashion Finesse",
    price: "1500",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Designer Men's Suit",
    brand: "Elegance Couture",
    price: "8000",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Casual Women's Top",
    brand: "Trendy Chic",
    price: "1200",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Formal Women's Blazer",
    brand: "Classy Attire",
    price: "4500",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Adorable Kids' Dress",
    brand: "Tiny Trends",
    price: "800",
    categoryName: "Kids' Clothing",
  },
  {
    _id: uuid(),
    title: "Men's Denim Jacket",
    brand: "Denim Co.",
    price: "2500",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Women's Floral Print Dress",
    brand: "Blossom Fashion",
    price: "1800",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Kids' Hooded Sweatshirt",
    brand: "Playful Kids",
    price: "600",
    categoryName: "Kids' Clothing",
  },
  {
    _id: uuid(),
    title: "Men's Leather Shoes",
    brand: "Classic Footwear",
    price: "3200",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    title: "Women's Handbag",
    brand: "Fashion Avenue",
    price: "900",
    categoryName: "Accessories",
  },
  {
    _id: uuid(),
    title: "Men's Polo Shirt",
    brand: "Polo Style",
    price: "1200",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Women's Skinny Jeans",
    brand: "Slim Fit",
    price: "1500",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Kids' Printed T-Shirt",
    brand: "Happy Prints",
    price: "400",
    categoryName: "Kids' Clothing",
  },
  {
    _id: uuid(),
    title: "Women's High Heels",
    brand: "Elegant Steps",
    price: "2800",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    title: "Men's Casual Trousers",
    brand: "Casual Comfort",
    price: "1800",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Women's Summer Dress",
    brand: "Sunshine Fashion",
    price: "2100",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Kids' Denim Shorts",
    brand: "Cool Kids",
    price: "500",
    categoryName: "Kids' Clothing",
  },
  {
    _id: uuid(),
    title: "Men's Formal Shirt",
    brand: "Elegant Attire",
    price: "1900",
    categoryName: "Men's Clothing",
  },
  {
    _id: uuid(),
    title: "Women's Cardigan",
    brand: "Cozy Knits",
    price: "1600",
    categoryName: "Women's Clothing",
  },
  {
    _id: uuid(),
    title: "Kids' Sportswear Set",
    brand: "Active Kids",
    price: "800",
    categoryName: "Kids' Clothing",
  },
  {
    _id: uuid(),
    title: "Men's Sports Shoes",
    brand: "Athletic Gear",
    price: "3500",
    categoryName: "Shoes",
  },
  {
    _id: uuid(),
    title: "Women's Scarf",
    brand: "Fashionista",
    price: "600",
    categoryName: "Accessories",
  },
];
